# Generated by Django 5.2.3 on 2025-08-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='resumen',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
