# Generated by Django 5.2.3 on 2025-08-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('nombre_usuario', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('imagen', models.ImageField(upload_to='usuarios')),
            ],
        ),
    ]
